# Generated by Django 4.1 on 2022-11-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('process', models.TextField()),
                ('uses', models.TextField()),
                ('others', models.CharField(max_length=3000)),
                ('conclusion', models.CharField(max_length=1000)),
                ('images', models.ImageField(upload_to='blogs/image/')),
            ],
        ),
    ]
