# Generated by Django 4.1 on 2022-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cropinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousCropPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('rain', models.IntegerField()),
                ('crop', models.CharField(max_length=100)),
            ],
        ),
    ]
