# Generated by Django 4.1 on 2022-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fertilizerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousFertilizerPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('moisture', models.IntegerField()),
                ('soil', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('fertilizer', models.CharField(max_length=100)),
            ],
        ),
    ]
