# Generated by Django 4.1 on 2022-11-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_previousfertilizerpred'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=200)),
                ('districtName', models.CharField(max_length=200)),
                ('cropYear', models.IntegerField()),
                ('season', models.CharField(max_length=200)),
                ('crop', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('production', models.FloatField()),
            ],
        ),
    ]
